export const SET_BOOKS = 'SET_BOOKS'
export const GET_BOOKS = 'GET_BOOKS'
export const SET_BOOK = 'SET_BOOK'
export const GET_BOOK = 'GET_BOOK'
export const OPEN_BOOK = 'OPEN_BOOK'
export const OPEN_MAIN_PAGE = 'OPEN_MAIN_PAGE'
export const NEXT_MAIN_PAGE = 'NEXT_MAIN_PAGE'
export const PREV_MAIN_PAGE = 'PREV_MAIN_PAGE'
